[package]
name = "rz-fuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
meson = "1.0.0"
bindgen = { git = "https://github.com/rust-lang/rust-bindgen.git", branch = "main" }
