[package]
name = "rizin-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arbitrary = { version = "1", features = ["derive"] }
bindgen = "0.69.4"

[build-dependencies]
#bindgen = { git = "https://github.com/rust-lang/rust-bindgen.git", branch = "main" }

