[package]
name = "rizin-sys"
version = "0.9.1"
edition = "2024"
license = "LGPL-3.0-only"
description = "Rust bindings for rizin"

[build-dependencies]
bindgen = "0.72.1"
glob = "0.3.3"
itertools = "0.14.0"
pkg-config = "0.3.32"

[profile.dev]
rpath = true

[lib]
doctest = false
