name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check rizin
      uses: actions/checkout@master
      with:
        repository: rizinorg/rizin
        ref: refs/heads/dev
        path: ${{ github.workspace }}/../rizin
    - name: Cache rizin
      id: cache-rizin
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/../rizin/build
        key: ${{ runner.os }}-rizin
        save-always: true
    - name: Build rizin
      working-directory: ${{ github.workspace }}/../rizin
      run: |
        pip install meson ninja PyYAML
        meson setup --debug --buildtype=release --prefix=$(realpath $HOME/.local) build
        ninja install -C build
    - name: Setup Rust nightly
      run: |
        rustup toolchain install nightly --profile minimal
        rustup default nightly
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: |
        export LD_LIBRARY_PATH=${HOME}/.local/lib/$(uname -m)-linux-gnu:${HOME}/.local/lib:${HOME}/.local/lib64:${LD_LIBRARY_PATH}
        cargo build --verbose
    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=${HOME}/.local/lib/$(uname -m)-linux-gnu:${HOME}/.local/lib:${HOME}/.local/lib64:${LD_LIBRARY_PATH}
        cargo test --verbose
