name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check rizin
      uses: actions/checkout@master
      with:
        repository: rizinorg/rizin
        ref: refs/heads/dev
        path: rizin
    - name: Build rizin
      run: |
        cd rizin
        pip install meson ninja PyYAML
        meson setup --debug --buildtype=release --prefix=$(realpath $HOME/.local) build
        ninja install -C build
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
