name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check rizin
      uses: actions/checkout@master
      with:
        repository: rizinorg/rizin
        ref: refs/heads/dev
        path: rizin
    - name: Cache rizin
      id: cache-rizin
      uses: actions/cache@v4
      with:
        path: rizin/build
        key: ${{ runner.os }}-rizin
    - name: Build rizin
      run: |
        cd rizin
        pip install meson ninja PyYAML
        meson setup --debug --buildtype=release --prefix=$(realpath $HOME/.local) build
        ninja install -C build
    - run: rustup toolchain install stable --profile minimal
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: |
        export LD_LIBRARY_PATH=${HOME}/lib/$(uname -m)-linux-gnu:${HOME}/lib:${HOME}/lib64:${LD_LIBRARY_PATH}
        cargo build --verbose
    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=${HOME}/lib/$(uname -m)-linux-gnu:${HOME}/lib:${HOME}/lib64:${LD_LIBRARY_PATH}
        cargo test --verbose
